/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-116435-g719e46f54c-20240727"
#endif /* AVUTIL_FFVERSION_H */
